version: "2"

services:
  redis:
    image: redis:latest
    ports:
      - '6379:6379'

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - '27017:27017'
    command: mongod